# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1200)),
                ('Description', models.TextField(default='default secription')),
                ('Location', models.CharField(default='My_location', max_length=1200)),
                ('Startdate', models.DateField(blank=True, null=True)),
                ('endtdate', models.DateField(blank=True, null=True)),
                ('categories', models.CharField(choices=[('comdey', 'comdey'), ('adventure', 'adventure'), ('action', 'action'), ('horror', 'horror')], default='True', max_length=100)),
                ('published', models.BooleanField(default='True')),
            ],
        ),
    ]
